# helpers.rb
require 'net/http'
require 'json'
require 'logger'

helpers do

  def verify_token(token_value)
    # TODO the app-key really should be a one-time signature generated by a
    # private key so that the matching public key on auth can verify it
    app_key = "5555"

    uri = URI.parse("http://auth.platform.local/tokens/#{token_value}?app-key=#{app_key}")
    request = Net::HTTP::Get.new(uri.to_s)
    response = Net::HTTP.start(uri.host, uri.port) {|http|
      http.request(request)
    }
    JSON.parse(response.body)
  end

  def invalidate_token(token_value)
    app_key = "5555"

    uri = URI.parse("http://auth.platform.local/tokens/#{token_value}?app-key=#{app_key}")
    request = Net::HTTP::Delete.new(uri.to_s)
    response = Net::HTTP.start(uri.host, uri.port) {|http|
      http.request(request)
    }
    JSON.parse(response.body)
  end

end

