development:
  sessions:
    default:
      database: platform_content_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: platform_content_test
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: platform_content
      hosts:
        - localhost:27017
